name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - run: npm ci

      - name: CommitLint
        uses: wagoid/commitlint-github-action@v5

      - name: Prettier
        run: npx prettier --check "src/**/*.{js,ts}"

      - name: ESLint
        run: npm run lint

      - name: Security audit
        run: npm audit --audit-level=moderate
        continue-on-error: true

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - run: npm ci
      - name: Jest Tests
        run: npm test
      - run: npm run build